KeyError: 'name'

File "C:\Users\ADITYA\Desktop\CAR POOLING\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\ADITYA\Desktop\CAR POOLING\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ADITYA\Desktop\CAR POOLING\app.py", line 135, in <module>
    main()
File "C:\Users\ADITYA\Desktop\CAR POOLING\app.py", line 84, in main
    show_drivers.show()
File "C:\Users\ADITYA\Desktop\CAR POOLING\screens\show_drivers.py", line 25, in show
    with st.expander(f"Driver: {driver['name']}"):
                                ~~~~~~^^^^^^^^
